name: Backend CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Secrets를 사용해 파일 생성
      - name: Create required files from secrets
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          JSON_CONFIG: ${{ secrets.JSON_CONFIG }}
        run: |
          mkdir -p src/main/resources
          echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
          echo "$JSON_CONFIG" > src/main/resources/tribal-environs-445107-e9-1f83e9cefbee.json

      - name: Verify file creation
        run: |
          ls -l src/main/resources
          cat src/main/resources/application.properties
          cat src/main/resources/tribal-environs-445107-e9-1f83e9cefbee.json

      - name: Clean build directory
        run: ./gradlew clean

      - name: Build Spring Boot application
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t jinu0125/tourservice .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push jinu0125/tourservice

      - name: Deploy to GCP
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script: |
            sudo su
            sudo docker stop $(sudo docker ps -a | grep tourservice | awk '{print $1}') || true
            sudo docker rm $(sudo docker ps -a | grep tourservice | awk '{print $1}') || true
            sudo docker pull jinu0125/tourservice
            sudo docker run -d -p 8090:8090 --name tourservice jinu0125/tourservice
