name: Backend CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Secrets를 사용해 파일 생성
      - name: Create required files from secrets
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
          JSON_CONFIG: ${{ secrets.JSON_CONFIG }}
        run: |
          mkdir -p src/main/resources
          echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
          echo "$JSON_CONFIG" > src/main/resources/tribal-environs-445107-e9-1f83e9cefbee.json

      - name: Build and test
    
      - name: 스프링부트 애플리케이션 install # (0)
        run: ./gradlew clean

      - name: 스프링부트 애플리케이션 빌드 # (1)
        run: ./gradlew build

      - name: 도커 이미지 빌드 # (2)
        run: docker build -t jinu0125/tourService .

      - name: Docker Hub 로그인 # (3)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Hub 퍼블리시 # (4)
        run: docker push  jinu0125/tourService

      - name: GCP 인스턴스 접속 및 애플리케이션 실행 # (5)
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.GCP_SSH_PORT }}
          script: |
            sudo su
            sudo docker stop $(sudo docker ps -a | grep tourService | awk '{print $1}') 
            sudo docker rm $(sudo docker ps -a | grep tourService | awk '{print $1}') 
            sudo docker pull jinu0125/tourService
            sudo docker run -d -p 9000:9000 --name tourService jinu0125/tourService
